-- MySQL Script generated by MySQL Workbench
-- Sun Dec  5 15:31:28 2021
-- Model: jason_db    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema jason_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jason_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jason_db` DEFAULT CHARACTER SET utf8 ;
USE `jason_db` ;

-- -----------------------------------------------------
-- Table `jason_db`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jason_db`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(15) NOT NULL,
  `lastname` VARCHAR(15) NOT NULL,
  `birthday` DATE NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO Users (firstname, lastname, birthday, email) VALUES ('Eleftheria', 'Th', now(), 'th.eleftheria@email.com');
INSERT INTO Users (firstname, lastname, birthday, email) VALUES ('Gennadios', 'Be', now(), 'be.gennadios@email.com');
INSERT INTO Users (firstname, lastname, birthday, email) VALUES ('Lysimachos', 'FleurDe', now(), 'fleurde.lysimachos@email.com');


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

